# -*- coding: utf-8 -*-
r"""XUAT 词典导出：项目库 → XUnity.AutoTranslator Translation 目录（0.50.0）。

深挖 XUnity.AutoTranslator 5.6.1 源码（resources/）的可移植能力之一：
工具的字段级写回是「改资产文件」路线，XUAT 是「运行时词典替换」路线——
两条路线互补。对写回高风险的游戏（脚本驱动文本/引擎字符串占多数、
静态资产可改文本有限），把项目库的译文导出成 XUAT 词典，让用户装
XUAT 插件运行时替换——**不写任何游戏文件，零写坏风险**（宁漏勿坏
的最高形态）。

格式权威（Utilities/TextHelper.cs，逐行核对）：
    行 = ``原文=译文``，Encode（EscapeNewlines）转义：
    ``//``→``\/\/``（两个字符都转义）、``\\``→``\\\\``、``=``→``\\=``、
    LF→``\\n``（字面反斜杠 n）、CR→``\\r``；其余字符原样。
    解码侧（ReadTranslationLineAndDecode）：一行最多一个未转义 ``=``
    （第二个 → 整行无效）；``//`` = 行内注释（出现在键段 → 整行无效，
    值段 → 值截断）——所以 Encode 把 ``//`` 整体转义；``%3D`` 旧式转义；
    ``\\uXXXX`` 支持；键值两侧空白保留（不 trim）。

目录布局（README + TextTranslationCache.cs）：
    ``<out>/Translation/<Lang>/Text/00_<游戏名>.txt``
    - XUAT 递归加载 Text/ 下全部 *.txt + *.zip（排除 ``*resizer.txt``）；
    - 加载顺序：``_AutoGeneratedTranslations.txt`` 最先；其余按
      ``OrderByDescending(IsZipped).ThenByDescending(FullName)``——
      后加载的覆盖先加载的 ⇒ 非 zip、文件名字典序**小**者优先级最高。
      ``00_`` 前缀保证我们的词典压过自动生成文件与用户已有词典；
    - ``<Lang>`` 取 XUAT 配置 ``[General] Language``（默认 en）——
      这是**目标语言**目录名，按惯例与游戏原语言一致命名（XUAT 以此
      目录名区分语言包），导出时由调用方指定，默认 ``zh``。

场景作用域（TranslationFileLoadingContext.cs）：
    ``#set level 1,2,3`` / ``#unset level`` 按场景 **buildIndex 整数**
    约束后续行（需 ``EnableTranslationScoping=True``，默认关）。项目库
    的 asset_file 名（level1 等）无法可靠映射 buildIndex，**统一导出为
    全局条目**——宁漏勿坏：作用域写错会导致文本不替换，全局条目
    语义与写回路线一致。

不做的（源码调研结论，防过度工程）：
    - 不生成空白变体键（加载侧自动生成 ExternallyTrimmed/FullyTrimmed
      变体并 4 形态查找，导出侧无需重复）；
    - 不加 ``\\u180e`` 重定向标记（MakeRedirected 加载时按需自动追加）；
    - 不带富文本模板参数化（``[[A]]``/``{{A}}`` 是运行时解析器行为；
      键保留完整标签文本，XUAT 按标签间片段查找可整体命中）；
    - ``r:``/``sr:`` 前缀键是正则翻译特性（RegexTranslationSplitter），
      我们的键是字面文本——以这两串开头的真文本必须跳过（会被 XUAT
      当正则解析，宁漏勿坏）。

**有损形态强制跳过（round-trip 闸门，源码实证）**：XUAT 的 ``//``
转义是**有损**的——Encode 把 ``//`` 写成 ``\\/\\/``，但
ReadTranslationLineAndDecode 的 default 分支对 ``\\/`` 不还原（保留
``\\/`` 两字符），词典键变成 ``\\/..`` 与游戏原文 ``//..`` 不匹配；
同理未转义的 ``%3D`` 被解码成 ``=``（旧式转义兼容）。含 ``//`` 或
``%3D`` 的文本在 XUAT 词典格式里**无法无损表示**——导出后要么静默
不命中（键不匹配）、要么显示错字（值被改写）。宁漏勿坏：每条导出前
做 Encode→Decode round-trip 校验（``xuat_decode`` 是
ReadTranslationLineAndDecode 的逐分支移植），不还原的条目跳过并在
文件头注释中计数透明化。
"""
from __future__ import annotations

import datetime
from pathlib import Path

__all__ = [
    "encode_xuat_line_value", "encode_xuat_entry", "export_xuat_translations",
    "xuat_decode", "XUAT_SKIPPED_PREFIXES",
]


def xuat_decode(line: str):
    """TextHelper.ReadTranslationLineAndDecode 的逐分支移植。

    供 round-trip 闸门与回归测试使用：返回 (key, value) / None（整行
    无效）。解码语义（对照源码）：``\\=``/``\\\\`` 还原字符、``\\n``/``\\r``
    还原换行、``\\uXXXX`` 还原码位、未知 ``\\x`` 保留两字符（有损根源
    之一：``\\/`` 不还原）、未转义 ``=`` 分隔键值（第二个 → 整行无效）、
    ``%3D`` → ``=``、``//`` 行内注释（键段 → 整行无效，值段 → 截断）。
    """
    if not line:
        return None
    lines = [None, None]
    lidx = 0
    escape_next = False
    builder: list[str] = []
    i, n = 0, len(line)
    while i < n:
        c = line[i]
        if escape_next:
            if c in ("=", "\\"):
                builder.append(c)
            elif c == "n":
                builder.append("\n")
            elif c == "r":
                builder.append("\r")
            elif c == "u":
                if i + 4 < n:
                    builder.append(chr(int(line[i + 1:i + 5], 16)))
                    i += 4
                else:
                    return None      # 源码 throw → 加载侧 catch 跳过该行
            else:
                builder.append("\\")
                builder.append(c)    # 有损：\/ 不还原
            escape_next = False
        elif c == "\\":
            escape_next = True
        elif c == "=":
            if lidx > 1:
                return None
            lines[lidx] = "".join(builder)
            lidx += 1
            builder = []
        elif c == "%":
            if i + 2 < n and line[i + 1] == "3" and line[i + 2] == "D":
                builder.append("=")
                i += 2
            else:
                builder.append(c)
        elif c == "/":
            if i + 1 < n and line[i + 1] == "/":
                lines[lidx] = "".join(builder)
                lidx += 1
                if lidx == 2:
                    return (lines[0], lines[1])   # 值段截断形态
                return None                       # 键段 → 整行无效
            builder.append(c)
        else:
            builder.append(c)
        i += 1
    if lidx != 1:
        return None
    lines[lidx] = "".join(builder)
    return (lines[0], lines[1])


def encode_xuat_line_value(text: str) -> str:
    """XUAT TextHelper.Encode（EscapeNewlines）的 Python 等价实现。

    转义规则逐字符核对自 TextHelper.cs EscapeNewlines：
    ``//``→``\\/\\/``、``\\``→``\\\\``、``=``→``\\=``、LF→``\\n``、
    CR→``\\r``。单根 ``/``（后面不是 ``/``）不转义——XUAT 解码侧只把
    ``//`` 当注释起始，单 ``/`` 原样通过。
    """
    if not text:
        return ""
    out: list[str] = []
    i = 0
    n = len(text)
    while i < n:
        c = text[i]
        if c == "/" and i + 1 < n and text[i + 1] == "/":
            out.append("\\/\\/")
            i += 2
        elif c == "\\":
            out.append("\\\\")
            i += 1
        elif c == "=":
            out.append("\\=")
            i += 1
        elif c == "\n":
            out.append("\\n")
            i += 1
        elif c == "\r":
            out.append("\\r")
            i += 1
        else:
            out.append(c)
            i += 1
    return "".join(out)


def encode_xuat_entry(key: str, value: str) -> str:
    """一条词典行：``encode(key)=encode(value)``。

    键值分别 Encode 后由未转义的 ``=`` 分隔——解码侧最多允许一个
    未转义 ``=``，Encode 已保证键值内部不再出现裸 ``=``。
    """
    return f"{encode_xuat_line_value(key)}={encode_xuat_line_value(value)}"


#: 键以这两串开头会被 XUAT 当正则指令解析（r:/sr:），字面文本跳过
XUAT_SKIPPED_PREFIXES = ("r:", "sr:")


def _iter_exportable_entries(store) -> tuple[list[dict], int]:
    """收集可导出条目：translated 状态 + 有译文 + 键不带正则前缀 +
    Encode→Decode round-trip 无损。

    skipped/failed/blocked 不导出（XUAT 只需要已确认译文；未翻译条目
    导出成空值只会覆盖成空白）。同键多行冲突（键是原文本身，同键即同
    原文，理论上不出现；出现时后写覆盖，与 XUAT 加载语义一致）按出现
    顺序去重，首见优先。

    返回 (entries, skipped_lossy)：skipped_lossy 是 round-trip 有损被
    跳过的条数（``//``/``%3D`` 形态——XUAT 词典格式无法无损表示，
    导出后要么不命中要么显示错字，宁漏勿坏跳过并计数透明化）。
    """
    rows = store.get_entries(status="translated")
    seen: set[str] = set()
    out: list[dict] = []
    skipped_lossy = 0
    for row in rows:
        key = (row.get("original") or "").strip()
        value = (row.get("translation") or "").strip()
        if not key or not value:
            continue          # 空键/空译文不导出（空译文 = 显示空白）
        if key.startswith(XUAT_SKIPPED_PREFIXES):
            continue          # XUAT 正则前缀——字面文本必跳（宁漏勿坏）
        if key in seen:
            continue
        seen.add(key)
        # round-trip 闸门：Encode 后经 XUAT 解码语义必须逐字符还原
        # 键与值（有损形态：// → \/ 不还原、%3D → = 改写）
        line = encode_xuat_entry(key, value)
        decoded = xuat_decode(line)
        if decoded != (key, value):
            skipped_lossy += 1
            continue
        out.append({"original": key, "translation": value})
    return out, skipped_lossy


def export_xuat_translations(project, out_dir: str | Path, *,
                             lang: str = "zh",
                             file_prefix: str = "00_",
                             filename: str | None = None,
                             ) -> Path | None:
    """把项目库译文导出为 XUAT Translation 词典。

    输出：``<out_dir>/Translation/<lang>/Text/<file_prefix><游戏名>.txt``
    （filename 显式指定时取代默认名）。UTF-8 无 BOM（XUAT 硬编码
    UTF-8 解码；BOM 会进第一行键首字节）。文件头带 ``//`` 注释块
    ——注释行是 XUAT 词典的合法行形态（ReadTranslationLineAndDecode
    返回 null 被跳过）。

    返回写入的词典文件路径；无可导出条目返回 None。
    game name 兜底链同 fail_export（profile.game_name → 未命名游戏），
    文件名不安全字符替换为下划线。
    """
    store = getattr(project, "store", None)
    if store is None:
        return None
    entries, skipped_lossy = _iter_exportable_entries(store)
    if not entries:
        return None
    profile = getattr(project, "profile", None)
    game = (getattr(profile, "game_name", None) or "未命名游戏").strip()
    safe_game = "".join(
        c if c not in '\\/:*?"<>|' else "_" for c in game) or "未命名游戏"

    name = filename if filename else f"{file_prefix}{safe_game}.txt"
    path = (Path(out_dir) / "Translation" / lang / "Text" / name).resolve()
    path.parent.mkdir(parents=True, exist_ok=True)

    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"// 由 UL10nForge 导出（{stamp}）",
        f"// 游戏：{game}",
        f"// 条目：{len(entries)}（仅包含已确认译文；键为游戏内原文，"
        f"XUAT 运行时替换显示，不修改任何游戏文件）",
        "// 放置：将 Translation 目录合并到 XUAT 的 "
        "AutoTranslator/Translation（BepInEx: BepInEx/Translation）",
        "// 优先级：00_ 前缀保证本词典覆盖 _AutoGeneratedTranslations.txt",
    ]
    if skipped_lossy:
        lines.append(
            f"// 注意：{skipped_lossy} 条含 // 或 %3D 的文本因 XUAT 词典"
            f"格式无法无损表示（转义有损）未导出——这类文本请走字段级写回")
    lines.extend(encode_xuat_entry(e["original"], e["translation"])
                 for e in entries)
    # UTF-8 无 BOM：XUAT ReadAllBytes→Encoding.UTF8.GetString，BOM 字节
    # 会成为第一行（注释行）的键首字符；newline 统一 \n（解码侧 \r\n
    # 会被 split 后残留 \r 进键尾——C# ReadLines 按行读不带 \r，Python
    # 写 \r\n 会在部分工具重读时引入歧义，统一 \n 最稳）
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return path
